management:
  health.db.enabled: false
  health.circuitbreakers.enabled: true
  health.ratelimiters.enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 4070
  servlet:
    context-path: /api/flights/clusters

  compression:
    enabled: true

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true
      latencyRangeStart: 10
      latencyRangeEnd: 5000

zookeeper:
  host: localhost:2181
  maxRetries: 2
  timeBetweenRetries: 100
  connectionTimeout: 1000 # 1 second

spring:
  profiles:
    active: default

  cache:
    redis:
      time-to-live: 300s  # 5 minutes

  redis:
    host: localhost
    port: 6079

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      recordExceptions:
        - java.lang.RuntimeException
        - java.lang.InterruptedException
        - io.netty.handler.timeout.ReadTimeoutException
        - org.springframework.web.reactive.function.client.WebClientRequestException
        - com.twa.flights.api.clusters.exception.TWAException
  backends:
    pricing:
      baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: true
      timeoutDuration: 1000ms  # time in secs a thread waits for a permission
      limitRefreshPeriod: 10s # period of time in secs for a limit to apply before refresh
      limitForPeriod: 2 # number of permissions during limit refresh period
  instances:
    availability:
      baseConfig: default

connector:
   catalog:
      host: localhost:6070
      responseTimeout: 2000
      connectionTimeout: 2000
      readTimeout: 2000
   pricing:
      host: localhost:5070
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000
   itineraries-search:
      host: localhost:7070
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000
