apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
        - name: varnish
          image: localhost:32000/twa-varnish:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
