management:
  health.db.enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 7070
  servlet:
    context-path: /api/flights/itineraries-search

  compression:
    enabled: true

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true
      latencyRangeStart: 10
      latencyRangeEnd: 12000

spring:
  profiles:
    active: default

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      recordExceptions:
        - java.lang.RuntimeException
        - java.lang.InterruptedException
        - io.netty.handler.timeout.ReadTimeoutException
        - org.springframework.web.reactive.function.client.WebClientRequestException
        - com.twa.flights.api.itineraries.search.exception.TWAException
  backends:
    provider-alpha:
      baseConfig: default
    provider-beta:
      baseConfig: default

connector:
   provider-alpha:
      host: localhost:8070
      responseTimeout: 5000
      connectionTimeout: 5000
      readTimeout: 5000
   provider-beta:
      host: localhost:9070
      responseTimeout: 5000
      connectionTimeout: 5000
      readTimeout: 5000
